### ISSUE TITLE
CopySource - Must be URL-encoded.

### ISSUE THREAD

**Issue by teebu** [newbreedofgeek/s3-bucket-cache-control#1]
Thanks for the code, just a heads up to people with special characters in their file names. 

CopySource — (String) The name of the source bucket and key name of the source object, separated by a slash (/). Must be URL-encoded.

http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#copyObject-property

**Comment by newbreedofgeek** [comment]
@teebu Thanks for the tip.
